services:
  admin:
    build:
      context: admin
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file: .env

  tunnel:
    build:
      context: tunnel
    command: ["start"]
    ports:
      - 2222:2222
      - 8001:8001
    depends_on:
      - admin
      - postgres
    env_file: .env

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
