services:
  caddy:
    # use a different tag than main
    image: ghcr.io/amalshaji/caddy-docker-proxy-cf:main
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  localport:
    build:
      # use an image
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./server.yaml:/app/config.yaml
      - ./data:/app/data/
      - ./keys:/app/keys/
    ports:
      - 8000:8000
      - 8001:8001
      - 2222:2222
    env_file: .env
    restart: unless-stopped
    labels:
      caddy_0: $DOMAIN
      caddy_0.reverse_proxy: "{{upstreams http 8000}}"
      caddy_0.encode: gzip
      caddy_1: "*.$DOMAIN"
      caddy_1.reverse_proxy: "{{upstreams http 8001}}"
      caddy_1.tls.dns: "cloudflare $CLOUDFLARE_API_TOKEN"
      caddy_1.encode: gzip

volumes:
  caddy_data: {}
