admin:
  port: 8000
  useVite: true
  oauth:
    clientId: $GITHUB_CLIENT_ID # this is replaced by the environment var
    clientSecret: $GITHUB_CLIENT_SECRET
ssh:
  port: 2222
proxy:
  port: 8001
database:
  url: $DATABASE_URL
  driver: sqlite3
  autoMigrate: true
useLocalhost: true
debug: true
domain: $DOMAIN
