admin:
  host: localhost
  port: 8000
  useVite: true
  oauth:
    clientId: $GITHUB_CLIENT_ID         # this is replaced by the environment var
    clientSecret: $GITHUB_CLIENT_SECRET 
  smtp:
    host: $SMTP_HOST
    port: 25
    username: $SMTP_USERNAME
    password: $SMTP_PASSWORD
    fromEmail: $SMTP_FROM_EMAIL
ssh:
  host: localhost
  port: 2222
proxy:
  host: localhost
  port: 8001
secure: false
debug: true
domain: $DOMAIN
