admin:
  port: 8000
  oauth:
    clientId: $GITHUB_CLIENT_ID # this is replaced by the environment var
    clientSecret: $GITHUB_CLIENT_SECRET
ssh:
  port: 2222
proxy:
  port: 8001
useLocalhost: true
debug: true
domain: $DOMAIN
databaseUrl: $DATABASE_URL
